language: go
go:
- 1.8
notifications:
  slack:
    secure: Lqo35ZPdsWoQPOmuBTcL8xzpo5a5EzShsbR2Z3cI70UMNaZjioUdi13XaCQXZAiVebH1Nh+7LM8zoJOgsoUDOAR3oHYEUZsE3Lej92sj+x0p7/Fvxs+5Mq6yvQIde8NY3VjnLMzhsEL81X9bTRQM8VwSA1zNPY2W+UqaK3ASrGofdrQH0wZm3UZtZu2OBzqYWvK1cRVRYU03VsPAgcMDku+geaOn04Z+Yf+BNuWyUSwiHRl8iPtYTGyjcCdEnxsauNpTS8u/is2PZ8/c1hmSZIl1N9hT5x9rn7NN9Q7yEkVVds6FEUZg5AhewPZdR44iRmjDK1Z+wyf1VQw5WBzHvScR7f0pAR7twVnQyMUNzt8p8uvN4M1kgr638oLG2dNszPcaZ5JYDjkdtalFYixudHDPs232kdlGazH7WwV4KbfPAlyfbXs8EGgI+OfTpa9qKy2z9PE1qbJuFBk01D1cxfR7foUXNOGxjWObr2wuVH2/E8WeODNQRtN7cCIEKOrCjl3IImuGbQAQpNpiZOxgkSDFpUI4ULKq8MD/PCCUD8q/qorlDwHwdOsDKj8e99fmhkIzGYbqeqUGcYk8PXDpLqLOWoVL15jxa9bO+9i/U/JD1pGoMMamItZJAE0IVPi6+5s8BJi+ELfiGkSLgk8z1PmWAth6M2bqDqYEnXAeiIE=
